---
- hosts: ad #在/etc/ansible/hosts配置文件中的ad组使用
  remote_user: root # 切换用户为root执行
  vars: 
    jarname:  # 需要上传和启动的jar包名称
      - web_socket-0.0.1-SNAPSHOT.jar
    srcpath: /home/bili/ # 控制机器上传文件夹
    destpath: /root/ # 受管节点文件夹
  tasks: 
   - name: copy jar to host # 循环读取jarname下的jar包名称，上传到受管节点
     copy: 
       src: "{{srcpath}}{{item}}"
       dest: "{{destpath}}{{item}}"
     loop: "{{jarname}}"
   - name: cd path
     shell: cd {{destpath}}
   - name: start jar # 循环读取jarname下的jar包名称并启动，异步执行，不需要接收返回值
     command: nohup /usr/java/jdk1.8.0_171/jre/bin/java -jar "{{destpath}}{{item}}" &
     async: 45
     poll: 0
     loop: "{{jarname}}"
