---
- hosts: ad
  remote_user: root
  vars: 
    jarname: 
      - web_socket-0.0.1-SNAPSHOT.jar
  tasks: 
   - name: stop jar if started
     shell: ps -fe | grep "{{item}}" | grep -v grep | tr -s " "|cut -d " " -f2 | xargs kill -9
     loop: "{{jarname}}"
